/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveFeatureProperties: typeof import('./src/components/ActiveFeatureProperties.vue')['default']
    FeatureInfoPanel: typeof import('./src/components/FeatureInfoPanel.vue')['default']
    FlashHighlight: typeof import('./src/components/FlashHighlight.vue')['default']
    InfoDialog: typeof import('./src/components/InfoDialog.vue')['default']
    LayerAttributeFilter: typeof import('./src/components/LayerAttributeFilter.vue')['default']
    LayerLegend: typeof import('./src/components/LayerLegend.vue')['default']
    LayerList: typeof import('./src/components/LayerList.vue')['default']
    MapComponent: typeof import('./src/components/MapComponent.vue')['default']
    MapLayer: typeof import('./src/components/MapLayer.vue')['default']
    MapZoomControl: typeof import('./src/components/MapZoomControl.vue')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
    NumberInput: typeof import('./src/components/NumberInput.vue')['default']
    ProcessRunButton: typeof import('./src/components/ProcessRunButton.vue')['default']
    RelatedGeometry: typeof import('./src/components/RelatedGeometry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionList: typeof import('./src/components/SelectionList.vue')['default']
    SubMenu: typeof import('./src/components/SubMenu.vue')['default']
  }
}
