/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AreaMenu: typeof import('./src/components/AreaMenu.vue')['default']
    copy: typeof import('./src/components/HazardMenu.vue')['default']
    HazardMenu: typeof import('./src/components/HazardMenu.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MapComponent: typeof import('./src/components/MapComponent.vue')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
